[package]
name = "proxy-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["serde"] }
chrono.workspace = true